select jsonb_build_object(
'tables',(select jsonb_agg(to_jsonb(x)) from(select n.nspname schema,c.relname name,c.relkind kind,c.relrowsecurity rls,c.relforcerowsecurity force_rls,c.relacl::text acl from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind in ('r','p','v','m','S'))x),
'columns',(select jsonb_agg(to_jsonb(x)) from(select n.nspname schema,c.relname "table",a.attname name,format_type(a.atttypid,a.atttypmod) type,a.attnotnull notnull,pg_get_expr(d.adbin,d.adrelid) "default",a.attidentity identity,a.attgenerated generated from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=c.oid and d.adnum=a.attnum where n.nspname in ('public','private') and c.relkind in ('r','p','v','m') and a.attnum>0 and not a.attisdropped)x),
'constraints',(select jsonb_agg(to_jsonb(x)) from(select conrelid::regclass::text "table",conname name,contype type,pg_get_constraintdef(oid,true) definition,convalidated validated from pg_constraint where connamespace in(select oid from pg_namespace where nspname in ('public','private')))x),
'indexes',(select jsonb_agg(to_jsonb(x)) from(select schemaname,tablename,indexname,indexdef from pg_indexes where schemaname in ('public','private'))x),
'policies',(select jsonb_agg(to_jsonb(x)) from(select * from pg_policies where schemaname in ('public','private','storage'))x),
'functions',(select jsonb_agg(to_jsonb(x)) from(select n.nspname schema,p.proname name,pg_get_function_identity_arguments(p.oid) args,pg_get_functiondef(p.oid) definition,p.proacl::text acl,p.provolatile volatility,p.prosecdef security_definer,p.proconfig config,p.proparallel parallel,p.proisstrict strict,p.proleakproof leakproof from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prokind='f')x),
'triggers',(select jsonb_agg(to_jsonb(x)) from(select c.relname "table",t.tgname name,t.tgenabled enabled,pg_get_triggerdef(t.oid,true) definition from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and not t.tgisinternal)x),
'enums',(select jsonb_agg(to_jsonb(x)) from(select n.nspname schema,t.typname name,e.enumlabel label,e.enumsortorder sort from pg_enum e join pg_type t on t.oid=e.enumtypid join pg_namespace n on n.oid=t.typnamespace where n.nspname in ('public','private'))x),
'schemas',(select jsonb_agg(to_jsonb(x)) from(select nspname name,nspacl::text acl from pg_namespace where nspname in ('public','private'))x),
'defaults',(select jsonb_agg(to_jsonb(x)) from(select r.rolname role,n.nspname schema,d.defaclobjtype type,d.defaclacl::text acl from pg_default_acl d join pg_roles r on r.oid=d.defaclrole left join pg_namespace n on n.oid=d.defaclnamespace where n.nspname in ('public','private') or d.defaclnamespace=0)x)
) as catalog;
