import "server-only";import {tasks as demoTasks} from "@/lib/demo-data";import {isDemoMode} from "@/lib/demo-mode";import {createClient} from "@/lib/supabase/server";
export type AdminTaskItem={id:string;clientId:string;client:string;title:string;description:string;category:string;assignedRole:string;due:string;priority:string;status:string;source:string};
export type AdminTaskData={items:AdminTaskItem[];clients:Array<{id:string;name:string}>;isDemo:boolean};
const titleCase=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
export async function loadAdminTasks():Promise<AdminTaskData>{
 if(isDemoMode())return{items:demoTasks.map((task,index)=>({id:`demo-task-${index+1}`,clientId:"demo-abc-interiors",client:task.client,title:task.title,description:"",category:index===0?"Social":"Operations",assignedRole:"Admin",due:task.due,priority:task.priority,status:task.status==="Blocked"?"Blocked":task.status==="Draft"?"Draft":"Awaiting Internal Review",source:"Manual"})),clients:[{id:"demo-abc-interiors",name:"ABC Interiors"},{id:"demo-smile-dental",name:"Smile Dental"},{id:"demo-xyz-maintenance",name:"XYZ Maintenance"}],isDemo:true};
 const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sign in as a partner.");const[{data:clients,error:clientError},{data:rows,error:taskError}]=await Promise.all([supabase.from("clients").select("id,name").is("deleted_at",null).order("name"),supabase.from("tasks").select("id,client_id,title,description,category,assigned_role,due_at,priority,status,source,clients(name)").order("due_at",{ascending:true,nullsFirst:false}).limit(300)]);if(clientError)throw clientError;if(taskError)throw taskError;
 const items=(rows??[]).map(row=>{const relation=row.clients as unknown as {name?:string}|{name?:string}[]|null,client=Array.isArray(relation)?relation[0]?.name:relation?.name;return{id:String(row.id),clientId:String(row.client_id),client:client??"Client",title:String(row.title),description:row.description??"",category:titleCase(String(row.category)),assignedRole:titleCase(String(row.assigned_role??"Unassigned")),due:row.due_at?new Intl.DateTimeFormat("en-AE",{day:"numeric",month:"short",year:"numeric",timeZone:"Asia/Dubai"}).format(new Date(row.due_at)):"No due date",priority:titleCase(String(row.priority)),status:titleCase(String(row.status)),source:titleCase(String(row.source))}});return{items,clients:(clients??[]).map(client=>({id:String(client.id),name:String(client.name)})),isDemo:false};
}
