import "server-only";
import {isDemoMode} from "@/lib/demo-mode";
import {createClient} from "@/lib/supabase/server";
import type {AnalyticsPoint,DataImport,SearchRow} from "@/lib/analytics-store";

export type AdminAnalyticsData={clients:Array<{id:string;name:string}>;selectedClientId:string;clientName:string;period:string;periodLabel:string;points:AnalyticsPoint[];searchRows:SearchRow[];imports:DataImport[];summary:{users:number;sessions:number;clicks:number;impressions:number};sources:{analytics:string;search:string};isDemo:boolean};
const demo:AdminAnalyticsData={clients:[{id:"demo-abc-interiors",name:"ABC Interiors"}],selectedClientId:"demo-abc-interiors",clientName:"ABC Interiors",period:"2026-09",periodLabel:"September 2026",points:[{day:"1 Sep",users:48,sessions:61,clicks:14,impressions:430},{day:"8 Sep",users:57,sessions:72,clicks:17,impressions:510},{day:"15 Sep",users:65,sessions:81,clicks:20,impressions:590},{day:"22 Sep",users:72,sessions:91,clicks:23,impressions:670},{day:"29 Sep",users:81,sessions:104,clicks:27,impressions:760}],searchRows:[{query:"villa renovation dubai",page:"/services/villa-renovation",clicks:148,impressions:1860,position:5.4},{query:"interior design company dubai",page:"/",clicks:121,impressions:2310,position:8.2},{query:"custom wardrobes dubai",page:"/services/wardrobes",clicks:84,impressions:970,position:6.8},{query:"kitchen renovation dubai",page:"/services/kitchens",clicks:73,impressions:1120,position:9.1}],imports:[{id:1,source:"Google Analytics 4",property:"Demo property · ABC Interiors",range:"1–30 Sep 2026",status:"Completed",rows:30,at:"30 Sep · 23:45",isDemo:true},{id:2,source:"Search Console",property:"Demo property · sc-domain:abcinteriors.ae",range:"1–30 Sep 2026",status:"Completed",rows:124,at:"30 Sep · 23:48",isDemo:true}],summary:{users:1842,sessions:2369,clicks:624,impressions:18420},sources:{analytics:"Demo",search:"Demo"},isDemo:true};
const metric=(value:unknown,key:string)=>Number((value as Record<string,unknown>|null)?.[key])||0;
const titleMonth=(period:string)=>new Intl.DateTimeFormat("en-AE",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${period}-01T00:00:00Z`));
const shortDate=(value:string)=>new Intl.DateTimeFormat("en-AE",{day:"numeric",month:"short",timeZone:"Asia/Dubai"}).format(new Date(value));

export async function loadAdminAnalytics(requestedClientId?:string,requestedPeriod?:string):Promise<AdminAnalyticsData>{
 if(isDemoMode())return demo;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sign in as a partner.");
 const{data:clientRows,error:clientError}=await supabase.from("clients").select("id,name").is("deleted_at",null).order("name");if(clientError)throw clientError;const clients=(clientRows??[]).map(row=>({id:String(row.id),name:String(row.name)})),selected=clients.find(client=>client.id===requestedClientId)??clients[0];if(!selected)return{...demo,clients:[],selectedClientId:"",clientName:"No client selected",points:[],searchRows:[],imports:[],summary:{users:0,sessions:0,clicks:0,impressions:0},sources:{analytics:"Not connected",search:"Not connected"},isDemo:false};
 const period=/^\d{4}-\d{2}$/.test(requestedPeriod??"")?requestedPeriod!:new Date().toISOString().slice(0,7),start=`${period}-01`,endDate=new Date(`${start}T00:00:00Z`);endDate.setUTCMonth(endDate.getUTCMonth()+1);const end=endDate.toISOString().slice(0,10);
 const[{data:analytics,error:analyticsError},{data:search,error:searchError},{data:imports,error:importError},{data:access,error:accessError}]=await Promise.all([supabase.from("analytics_daily").select("day,metrics").eq("client_id",selected.id).gte("day",start).lt("day",end).order("day"),supabase.from("search_console_daily").select("day,query,page,metrics").eq("client_id",selected.id).gte("day",start).lt("day",end).order("day"),supabase.from("data_imports").select("id,source,source_property,date_from,date_to,status,is_demo,row_count,error_message,imported_at").eq("client_id",selected.id).order("imported_at",{ascending:false}).limit(20),supabase.from("client_access").select("access_type,status").eq("client_id",selected.id)]);if(analyticsError)throw analyticsError;if(searchError)throw searchError;if(importError)throw importError;if(accessError)throw accessError;
 const byDay=new Map<string,AnalyticsPoint>();for(const row of analytics??[]){const key=String(row.day),current=byDay.get(key)??{day:shortDate(key),users:0,sessions:0,clicks:0,impressions:0};current.users+=metric(row.metrics,"users")||metric(row.metrics,"activeUsers")||metric(row.metrics,"visitors");current.sessions+=metric(row.metrics,"sessions");byDay.set(key,current)}for(const row of search??[]){const key=String(row.day),current=byDay.get(key)??{day:shortDate(key),users:0,sessions:0,clicks:0,impressions:0};current.clicks+=metric(row.metrics,"clicks");current.impressions+=metric(row.metrics,"impressions");byDay.set(key,current)}
 const queryMap=new Map<string,SearchRow&{positionWeight:number}>();for(const row of search??[]){if(!row.query)continue;const key=`${row.query}|${row.page}`,clicks=metric(row.metrics,"clicks"),impressions=metric(row.metrics,"impressions"),position=metric(row.metrics,"position"),current=queryMap.get(key)??{query:String(row.query),page:String(row.page||"/"),clicks:0,impressions:0,position:0,positionWeight:0};current.clicks+=clicks;current.impressions+=impressions;current.position+=position*Math.max(impressions,1);current.positionWeight+=Math.max(impressions,1);queryMap.set(key,current)}
 const points=[...byDay.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([,value])=>value),searchRows=[...queryMap.values()].map(({positionWeight,...row})=>({...row,position:Number((row.position/positionWeight).toFixed(1))})).sort((a,b)=>b.clicks-a.clicks).slice(0,12),summary=points.reduce((total,row)=>({users:total.users+row.users,sessions:total.sessions+row.sessions,clicks:total.clicks+row.clicks,impressions:total.impressions+row.impressions}),{users:0,sessions:0,clicks:0,impressions:0});
 const formattedImports:DataImport[]=(imports??[]).map((row,index)=>({id:index+1,source:row.source==="google_analytics"?"Google Analytics 4":"Search Console",property:String(row.source_property),range:`${shortDate(row.date_from)}–${shortDate(row.date_to)}`,status:String(row.status).replace(/^./,c=>c.toUpperCase()) as DataImport["status"],rows:Number(row.row_count),at:shortDate(row.imported_at),isDemo:Boolean(row.is_demo),error:row.error_message??undefined})),status=(name:string)=>String((access??[]).find(row=>String(row.access_type).toLowerCase().includes(name))?.status??"not_connected").replaceAll("_"," ").replace(/^./,c=>c.toUpperCase());
 return{clients,selectedClientId:selected.id,clientName:selected.name,period,periodLabel:titleMonth(period),points,searchRows,imports:formattedImports,summary,sources:{analytics:status("analytics"),search:status("search console")},isDemo:false};
}
