"use client";
import { useSyncExternalStore } from "react";
import { posts as seed } from "./demo-data";
export type SocialStatus =
  | "Idea"
  | "Generating"
  | "Needs review"
  | "Approved"
  | "Ready for Design"
  | "Poster Created"
  | "Ready to schedule"
  | "Scheduled"
  | "Published"
  | "Issue";
export type SocialPost = {
  id: number | string;
  clientId?: string;
  client: string;
  month: string;
  date: string;
  time: string;
  platform: string;
  contentType: string;
  postNumber: number;
  topic: string;
  objective: string;
  posterHeadline: string;
  posterSupportingText: string;
  concept: string;
  caption: string;
  hashtags: string;
  creativeBrief: string;
  notes: string;
  issueNote: string;
  status: SocialStatus;
  color: string;
  history: string[];
  imagePrompt: string;
  cta: string;
  imageModel: string;
  imageVersion: number;
  imageStatus: "Placeholder" | "Generated" | "Failed";
  storagePath: string | null;
  imageUrl?: string | null;
  assignedStaff?: string | null;
};
let current: SocialPost[] = seed.map((p) => ({
  ...p,
  client: "ABC Interiors",
  month: "November 2026",
  contentType: p.platform.includes("Instagram") ? "Carousel" : "Single image",
  postNumber: Number(p.id),
  objective: "Build consideration with useful, verified guidance.",
  posterHeadline: p.topic,
  posterSupportingText: "",
  concept: `A practical, design-led post about ${p.topic.toLowerCase()} for Dubai homeowners.`,
  hashtags: "#DubaiInteriors #InteriorDesignUAE #HomeRenovation",
  creativeBrief: `Editorial interior composition in ${p.color} tones, premium natural light, no text overlay.`,
  notes: "Use verified services and locations only.",
  issueNote: "",
  status: p.status as SocialStatus,
  history: [`Seeded as ${p.status}`],
  imagePrompt: `Editorial interior composition for ${p.topic}.`,
  cta: "Start a WhatsApp consultation",
  imageModel: "demo-placeholder",
  imageVersion: 1,
  imageStatus: "Placeholder",
  storagePath: null,
}));
const initial = current;
const listeners = new Set<() => void>();
function emit() {
  listeners.forEach((listener) => listener());
}
export function useSocialPosts() {
  return useSyncExternalStore(
    (listener) => {
      listeners.add(listener);
      return () => listeners.delete(listener);
    },
    () => current,
    () => initial,
  );
}
export function updateSocialPost(
  id: number | string,
  patch: Partial<SocialPost>,
  activity?: string,
) {
  current = current.map((p) =>
    p.id === id
      ? {
          ...p,
          ...patch,
          history: activity ? [activity, ...p.history] : p.history,
        }
      : p,
  );
  emit();
}
export function updateSocialPosts(
  ids: Array<number | string>,
  patch: Partial<SocialPost>,
  activity: string,
) {
  current = current.map((p) =>
    ids.includes(p.id)
      ? { ...p, ...patch, history: [activity, ...p.history] }
      : p,
  );
  emit();
}
export function resetSocialStore() {
  current = initial.map((p) => ({ ...p, history: [...p.history] }));
  emit();
}
export function addGeneratedSocialPlan(
  month: string,
  concepts: Array<{
    postNumber: number;
    contentType: string;
    topic: string;
    objective: string;
    platform: string;
    suggestedDate: string;
    suggestedTime: string;
    posterHeadline: string;
    posterSupportingText: string;
    concept?: string;
    caption: string;
    cta: string;
    hashtags: string;
    creativeBrief: string;
    imagePrompt: string;
    internalNotes: string;
  }>,
  provider: string,
  model: string,
) {
  const [year, monthNumber] = month.split("-").map(Number),
    monthLabel = new Intl.DateTimeFormat("en", {
      month: "long",
      year: "numeric",
      timeZone: "UTC",
    }).format(new Date(Date.UTC(year, monthNumber - 1, 1)));
  const palette = ["lavender", "sage", "sand", "blue"];
  const additions = concepts.map((item, index): SocialPost => ({
    id: Date.now() + index,
    client: "ABC Interiors",
    month: monthLabel,
    date: new Intl.DateTimeFormat("en",{day:"2-digit",month:"short",timeZone:"UTC"}).format(new Date(`${item.suggestedDate}T00:00:00Z`)),
    time: item.suggestedTime,
    ...item,
    concept:item.concept??item.objective,
    notes: item.internalNotes,
    issueNote: "",
    status: "Needs review",
    color: palette[index % palette.length],
    history: [
      `Generated by ${provider} · ${model}`,
      "Image placeholder created",
      "Set to Needs review",
    ],
    imagePrompt: item.imagePrompt,
    imageModel: "manual-production",
    imageVersion: 1,
    imageStatus: "Placeholder",
    storagePath: null,
  }));
  current = [...current.filter((p) => p.month !== monthLabel), ...additions];
  emit();
}
export function regenerateSocialImage(id: number | string) {
  current = current.map((p) =>
    p.id === id
      ? {
          ...p,
          imageVersion: p.imageVersion + 1,
          imageStatus: "Placeholder",
          storagePath: null,
          history: [
            `Image placeholder regenerated · v${p.imageVersion + 1}`,
            ...p.history,
          ],
        }
      : p,
  );
  emit();
}
export const getSocialSnapshot = () => current;
