"use client";
import Link from "next/link";
import {useMemo,useState,useTransition} from "react";
import {Check,ExternalLink,RotateCcw} from "lucide-react";
import {decideApproval} from "@/app/admin/approvals/actions";
import type {ApprovalItem,ApprovalKind} from "@/lib/admin-approval-data";
import {Status} from "./ui";
const labels:Record<ApprovalKind,string>={social:"Social",blog:"Blog",seo:"SEO"},routes:Record<ApprovalKind,string>={social:"/admin/content",blog:"/admin/blogs",seo:"/admin/seo"};
export function ApprovalQueue({initial,isDemo}:{initial:ApprovalItem[];isDemo:boolean}){const[items,setItems]=useState(initial),[kind,setKind]=useState("All work"),[notice,setNotice]=useState(""),[pending,startTransition]=useTransition(),visible=useMemo(()=>kind==="All work"?items:items.filter(item=>labels[item.kind]===kind),[items,kind]),social=items.filter(item=>item.kind==="social");function decide(item:ApprovalItem,decision:"approve"|"revision"){if(isDemo){setItems(rows=>rows.filter(row=>row.id!==item.id));setNotice(`${item.title} ${decision==="approve"?"approved":"returned for revision"} in demo mode.`);return}startTransition(async()=>{const result=await decideApproval(item.kind,item.id,item.clientId,decision);if(result.ok){setItems(rows=>rows.filter(row=>row.id!==item.id));setNotice(decision==="approve"?"Approval recorded and work advanced.":"Revision request recorded.")}else setNotice(result.error)})}function batch(){if(isDemo){setItems(rows=>rows.filter(item=>item.kind!=="social"));setNotice(`${social.length} safe social items approved in demo mode.`);return}startTransition(async()=>{const results=await Promise.all(social.map(item=>decideApproval(item.kind,item.id,item.clientId,"approve"))),failed=results.filter(result=>!result.ok);if(failed.length)setNotice(`${social.length-failed.length} approved; ${failed.length} could not be updated.`);else{setItems(rows=>rows.filter(item=>item.kind!=="social"));setNotice(`${social.length} social items approved and sent to Staff.`)}})}return <>{notice&&<div className="toast" role="status">{notice}</div>}<div className="toolbar"><select aria-label="Approval type" value={kind} onChange={event=>setKind(event.target.value)}><option>All work</option><option>Social</option><option>Blog</option><option>SEO</option></select><button className="button" disabled={pending||!social.length} onClick={batch}><Check size={14}/>Approve safe social items ({social.length})</button><span style={{fontSize:11,color:"var(--muted)",alignSelf:"center"}}>{items.length} awaiting review</span></div><div>{visible.map(item=><div className="task-item" key={`${item.kind}-${item.id}`}><div><b>{item.title}</b><p>{item.client} · {item.detail}</p></div><div className="approval-actions"><Status tone="warn">{item.status}</Status><Link className="button secondary" href={routes[item.kind]}><ExternalLink size={12}/>Open</Link><button className="button secondary" disabled={pending} onClick={()=>decide(item,"revision")}><RotateCcw size={12}/>Revision</button><button className="button" disabled={pending} onClick={()=>decide(item,"approve")}><Check size={12}/>Approve</button></div></div>)}{!visible.length&&<div className="empty-state"><b>Review queue clear</b><p>Approved work is ready for its next internal operational step.</p></div>}</div></>}
