"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, CheckCircle2, Clock3, Pause, Play, RefreshCw, Workflow } from "lucide-react";
import { runAutomationNow, setAutomationStatus, syncGoogleNow } from "@/app/admin/automations/actions";
import type { AdminAutomationData } from "@/lib/admin-automation-data";
import { retryRun, runAutomation, setJobStatus, useAutomationErrors, useAutomationJobs, useAutomationRuns } from "@/lib/automation-store";
import { Panel, Status } from "./ui";

export function AutomationDashboard({ initial }: { initial: AdminAutomationData }) {
  const demoJobs = useAutomationJobs(), demoRuns = useAutomationRuns(), demoErrors = useAutomationErrors();
  const jobs = initial.isDemo ? demoJobs : initial.jobs, runs = initial.isDemo ? demoRuns : initial.runs, errors = initial.isDemo ? demoErrors : initial.errors;
  const [tab, setTab] = useState<"Runs" | "Failures">("Runs"), [clientId, setClientId] = useState(initial.clients[0]?.id ?? ""), [notice, setNotice] = useState(""), [pending, startTransition] = useTransition(), router = useRouter();
  const healthy = jobs.filter((job) => job.health === "Healthy").length, running = jobs.filter((job) => job.health === "Running").length, failed = jobs.filter((job) => job.health === "Failed").length;
  function toggle(job: (typeof jobs)[number]) { if (initial.isDemo) { setJobStatus(job.id, job.status === "Active" ? "Paused" : "Active"); setNotice(`${job.name} ${job.status === "Active" ? "paused" : "activated"}.`); return; } const dbId = job.dbId; if (!dbId) return; startTransition(async () => { const result = await setAutomationStatus(dbId, job.status === "Active" ? "paused" : "active"); setNotice(result.ok ? `${job.name} ${job.status === "Active" ? "paused" : "activated"}.` : result.error); if (result.ok) router.refresh(); }); }
  function run(job: (typeof jobs)[number]) { if (initial.isDemo) { runAutomation(job.id); setNotice(`${job.name} started in demo mode.`); return; } const dbId = job.dbId; if (!dbId) return; startTransition(async () => { const result = await runAutomationNow(dbId, clientId); setNotice(result.ok ? `${job.name} queued in n8n.` : result.error); router.refresh(); }); }
  function syncGoogle() { startTransition(async () => { const result = await syncGoogleNow(clientId); setNotice(result.ok ? "Google Analytics and Search Console synced for the last 90 days." : result.error); if (result.ok) router.refresh(); }); }
  function retry(runId: number) { if (initial.isDemo) { retryRun(runId); setNotice("Retry started in demo mode."); return; } const failedRun = runs.find((item) => item.id === runId), job = jobs.find((item) => item.dbId === failedRun?.jobDbId); if (job) run(job); }
  return <>
    {notice && <div className="generation-notice" role="status"><Workflow size={15}/><span>{notice}</span></div>}
    <div className="automation-stats"><div><CheckCircle2/><span><b>{healthy}</b>Healthy</span></div><div><Clock3/><span><b>{running}</b>Running</span></div><div><AlertTriangle/><span><b>{failed}</b>Failed</span></div></div>
    <Panel title="Reusable workflows" meta="One parameterized workflow serves every client" action={!initial.isDemo && <div className="run-tabs"><select aria-label="Run workflow for client" value={clientId} onChange={(event) => setClientId(event.target.value)}>{initial.clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select><button className="button secondary" disabled={pending || !clientId} onClick={syncGoogle}><RefreshCw size={12}/>Sync Google data</button></div>}>
      <div className="workflow-grid">{jobs.map((job) => <article className="workflow-card" key={job.dbId ?? job.id}><header><span className={`workflow-icon ${job.health.toLowerCase()}`}><Workflow/></span><Status tone={job.health === "Failed" ? "warn" : job.health === "Running" ? "purple" : ""}>{job.health}</Status></header><h3>{job.name}</h3><code>{job.key}(client_id{job.key !== "SEO_REVIEW" ? ", month" : ""})</code><dl><div><dt>Schedule</dt><dd>{job.schedule}</dd></div><div><dt>Last run</dt><dd>{job.lastRun}</dd></div><div><dt>Next run</dt><dd>{job.nextRun}</dd></div></dl><footer><button className="button secondary" disabled={pending} onClick={() => toggle(job)}>{job.status === "Active" ? <Pause size={12}/> : <Play size={12}/>} {job.status}</button><button className="button" disabled={pending || job.health === "Running" || !clientId} onClick={() => run(job)}><Play size={12}/>Run now</button></footer></article>)}</div>
    </Panel>
    <Panel title="Run history" meta="Inputs, outputs, cost and visible failures" action={<div className="run-tabs"><button className={tab === "Runs" ? "active" : ""} onClick={() => setTab("Runs")}>All runs</button><button className={tab === "Failures" ? "active" : ""} onClick={() => setTab("Failures")}>Failures ({errors.length})</button></div>}>
      {tab === "Runs" ? <div className="run-table"><div className="run-head"><span>Workflow</span><span>Client / input</span><span>Status</span><span>Output</span><span>Cost</span></div>{runs.length ? runs.map((run) => <div className="run-row" key={run.dbId ?? run.id}><span><b>{run.workflow}</b><small>{run.started}</small></span><span><b>{run.client}</b><small>{run.input}</small></span><Status tone={run.status === "Failed" ? "warn" : run.status === "Running" ? "purple" : ""}>{run.status}</Status><span>{run.output}</span><span>{run.cost === null ? "—" : `$${run.cost.toFixed(4)}`}</span></div>) : <div className="empty-state"><b>No workflow runs yet.</b><p>Run a workflow for a client to create the first traceable record.</p></div>}</div> : <div>{errors.length ? errors.map((error) => { const runRecord = runs.find((run) => run.id === error.runId); return <div className="failure-row" key={error.runDbId ?? error.runId}><AlertTriangle/><div><b>{error.code}</b><p>{error.message}</p><small>{runRecord?.workflow} · {runRecord?.client} · {error.time}</small></div><button className="button secondary" disabled={pending} onClick={() => retry(error.runId)}><RefreshCw size={12}/>Retry</button></div>; }) : <div className="empty-state"><b>No automation failures.</b><p>Workflow errors will appear here with a retry action.</p></div>}</div>}
    </Panel>
    <div className="automation-note"><b>Human-controlled boundary</b><span>Automations create reviewable work only. Social publishing and website publishing remain manual.</span></div>
  </>;
}
