"use client";
import {useMemo,useState} from "react";import {CalendarDays,Check,ChevronLeft,ChevronRight,ImageIcon,Pencil,RotateCcw,Sparkles,X} from "lucide-react";import {generateSocialMonth,regenerateSocialCreative,saveSocialContent} from "@/app/admin/content/actions";import {addGeneratedSocialPlan,regenerateSocialImage,SocialPost,SocialStatus,updateSocialPost,useSocialPosts} from "@/lib/social-store";import {DemoAIProvider} from "@/lib/ai/demo-provider";import {prepareMonthlySocial} from "@/lib/ai/monthly-social";import {Status} from "./ui";
const statuses:SocialStatus[]=["Idea","Generating","Needs review","Approved","Ready to schedule","Scheduled","Published","Issue"],monthKeys=["2026-09","2026-10","2026-11","2026-12"] as const;
const monthLabel=(key:string)=>new Intl.DateTimeFormat("en",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${key}-01T00:00:00Z`));
const dbStatus:Record<SocialStatus,string>={Idea:"idea",Generating:"generating","Needs review":"needs_review",Approved:"approved","Ready to schedule":"ready_to_post",Scheduled:"scheduled",Published:"published",Issue:"issue"};
type Props={initial:SocialPost[];clients:Array<{id:string;name:string}>;isDemo:boolean};

export function SocialOperations({initial,clients,isDemo}:Props){
 const demoPosts=useSocialPosts(),[livePosts,setLivePosts]=useState(initial),posts=isDemo?demoPosts:livePosts;
 const[filter,setFilter]=useState("All statuses"),[platform,setPlatform]=useState("All platforms"),[editing,setEditing]=useState<SocialPost|null>(null),[month,setMonth]=useState("2026-11"),[clientId,setClientId]=useState(clients[0]?.id??""),[generating,setGenerating]=useState(false),[imageGenerating,setImageGenerating]=useState(false),[notice,setNotice]=useState("");
 const monthPosts=posts.filter(post=>post.month===monthLabel(month)&&(isDemo||post.clientId===clientId)),visible=useMemo(()=>monthPosts.filter(post=>(filter==="All statuses"||post.status===filter)&&(platform==="All platforms"||post.platform.includes(platform))),[monthPosts,filter,platform]);
 const counts={review:monthPosts.filter(post=>post.status==="Needs review").length,ready:monthPosts.filter(post=>post.status==="Ready to schedule").length,scheduled:monthPosts.filter(post=>post.status==="Scheduled").length,published:monthPosts.filter(post=>post.status==="Published").length};
 const moveMonth=(direction:number)=>{const index=monthKeys.indexOf(month as typeof monthKeys[number]);setMonth(monthKeys[Math.max(0,Math.min(monthKeys.length-1,index+direction))])};
 async function generate(){setGenerating(true);setNotice("");try{if(isDemo){const result=await prepareMonthlySocial(new DemoAIProvider(),month,12);addGeneratedSocialPlan(month,result.concepts,result.provider,result.model);setNotice(`12 posts prepared with ${result.model}. Demo image placeholders are ready for review.`)}else{const result=await generateSocialMonth(clientId,month);if(!result.ok)throw new Error(result.error);setNotice("12 posts prepared from verified client knowledge and moved to internal review.");window.location.reload()}}catch(error){setNotice(error instanceof Error?error.message:"Generation failed")}finally{setGenerating(false)}}
 async function save(post:SocialPost,next:SocialStatus){if(isDemo){updateSocialPost(post.id,{...post,status:next},`Updated content · ${next}`);setEditing(null);return}const result=await saveSocialContent(post,dbStatus[next]);if(!result.ok){setNotice(result.error);return}setLivePosts(rows=>rows.map(row=>row.id===post.id?{...post,status:next}:row));setNotice(next==="Ready to schedule"?"Approved and sent to the staff posting queue.":"Content changes saved.");setEditing(null)}
 async function regenerate(post:SocialPost){if(isDemo){regenerateSocialImage(post.id);return}setImageGenerating(true);const result=await regenerateSocialCreative(String(post.id),post.clientId??clientId);if(!result.ok)setNotice(result.error);else{setLivePosts(rows=>rows.map(row=>row.id===post.id?{...row,imageVersion:result.image.version,imageStatus:result.image.status,imageModel:result.image.model,storagePath:result.image.storagePath,history:[`Image placeholder regenerated · v${result.image.version}`,...row.history]}:row));setNotice(`Image version ${result.image.version} is ready for generation.`)}setImageGenerating(false)}
 return <>{notice&&<div className="generation-notice"><Sparkles size={15}/><span>{notice}</span></div>}<div className="content-summary"><div><span>Needs review</span><b>{counts.review}</b></div><div><span>Ready to schedule</span><b>{counts.ready}</b></div><div><span>Scheduled</span><b>{counts.scheduled}</b></div><div><span>Published</span><b>{counts.published}</b></div></div><div className="content-toolbar"><div className="month-switch"><button onClick={()=>moveMonth(-1)} aria-label="Previous month"><ChevronLeft size={14}/></button><b><CalendarDays size={14}/>{monthLabel(month)}</b><button onClick={()=>moveMonth(1)} aria-label="Next month"><ChevronRight size={14}/></button></div>{!isDemo&&<select aria-label="Client filter" value={clientId} onChange={event=>setClientId(event.target.value)}>{clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select>}<select value={platform} onChange={event=>setPlatform(event.target.value)} aria-label="Platform filter"><option>All platforms</option><option>Instagram</option><option>Facebook</option></select><select value={filter} onChange={event=>setFilter(event.target.value)} aria-label="Status filter"><option>All statuses</option>{statuses.map(status=><option key={status}>{status}</option>)}</select><button className="button generate-button" disabled={generating||!clientId} onClick={generate}><Sparkles size={13}/>{generating?"Preparing…":monthPosts.length?"Regenerate month":"Generate 12 posts"}</button></div>{visible.length?<div className="social-grid">{visible.map(post=><article className="social-card" key={post.id}><div className={`social-visual ${post.color}`}><span>{post.topic}</span><small>{post.date}</small><i><ImageIcon size={11}/>{post.imageStatus} v{post.imageVersion}</i></div><div className="social-card-body"><div className="social-card-top"><span>{post.platform}</span><Status tone={post.status==="Needs review"?"warn":post.status==="Issue"?"risk":post.status==="Scheduled"?"purple":""}>{post.status}</Status></div><h3>{post.topic}</h3><p>{post.caption}</p><div className="social-card-foot"><span>{post.time}</span><button onClick={()=>setEditing(post)}><Pencil size={12}/>Open</button></div></div></article>)}</div>:<div className="empty-state social-empty"><Sparkles/><b>No content prepared for {monthLabel(month)}</b><p>Generate 12 social posts from the selected client’s verified business knowledge.</p><button className="button" disabled={!clientId} onClick={generate}>Generate 12 posts</button></div>}{editing&&<Editor post={posts.find(post=>post.id===editing.id)??editing} close={()=>setEditing(null)} save={save} regenerate={regenerate} imageGenerating={imageGenerating}/>}</>
}

function Editor({post,close,save,regenerate,imageGenerating}:{post:SocialPost;close:()=>void;save:(post:SocialPost,status:SocialStatus)=>Promise<void>;regenerate:(post:SocialPost)=>Promise<void>;imageGenerating:boolean}){const[draft,setDraft]=useState(post),[tab,setTab]=useState("Content");return <div className="drawer-backdrop" onClick={close}><aside className="editor-drawer" onClick={event=>event.stopPropagation()}><header><div><span className="eyebrow">{post.client} · {post.date}</span><h2>{post.topic}</h2></div><button className="ghost-icon" onClick={close} aria-label="Close editor"><X size={19}/></button></header><div className={`editor-preview ${post.color}`}><span>{post.topic}</span><small>{post.imageStatus} creative · version {post.imageVersion}</small></div><div className="image-meta"><span><b>Image model</b>{post.imageModel}</span><span><b>Storage</b>{post.storagePath??"No generated asset yet"}</span></div><div className="editor-tabs"><button className={tab==="Content"?"active":""} onClick={()=>setTab("Content")}>Content</button><button className={tab==="History"?"active":""} onClick={()=>setTab("History")}>Activity</button></div>{tab==="Content"?<div className="editor-form"><label>Post concept<textarea value={draft.concept} onChange={event=>setDraft({...draft,concept:event.target.value})}/></label><label>Caption<textarea className="caption-area" value={draft.caption} onChange={event=>setDraft({...draft,caption:event.target.value})}/></label><label>Hashtags<input value={draft.hashtags} onChange={event=>setDraft({...draft,hashtags:event.target.value})}/></label><label>Creative brief<textarea value={draft.creativeBrief} onChange={event=>setDraft({...draft,creativeBrief:event.target.value})}/></label><label>Internal notes<textarea value={draft.notes} onChange={event=>setDraft({...draft,notes:event.target.value})}/></label></div>:<div className="history-list">{post.history.map((item,index)=><div key={`${item}-${index}`}><i/><span><b>{item}</b><small>Growth1000 · Partner</small></span></div>)}</div>}<footer><button className="button secondary" disabled={imageGenerating} onClick={()=>regenerate(post)}><RotateCcw size={13}/>{imageGenerating?"Preparing…":"Regenerate image"}</button><span/><button className="button secondary" onClick={()=>save(draft,draft.status)}>Save draft</button>{post.status==="Needs review"&&<button className="button" onClick={()=>save(draft,"Ready to schedule")}><Check size={13}/>Approve to staff</button>}</footer></aside></div>}
