import type { AIProvider,GenerationContext,GenerationResult } from "./provider";

const ideas=[
 ["Renovation planning order","A clear sequence for starting a renovation without avoidable rework."],
 ["Kitchen storage audit","Questions homeowners can use to plan storage around daily routines."],
 ["Villa zoning ideas","How lighting, rugs and joinery can define open-plan zones."],
 ["Wardrobe planning","Start with what needs to fit before choosing finishes."],
 ["Material longevity","Choose calm, durable materials suited to everyday Dubai living."],
 ["Design consultation prep","What to bring to an initial interior design conversation."],
 ["Fit-out communication","Why scope, updates and quality checks matter during delivery."],
 ["Small-space function","Use integrated storage to create calmer apartment interiors."],
 ["Lighting layers","Combine ambient, task and accent lighting with a clear purpose."],
 ["Before-and-after story","Explain the design decisions behind a verified project transformation."],
 ["Site coordination","Show how drawings and trade coordination protect the design intent."],
 ["Homeowner questions","Useful questions to ask before appointing a renovation partner."],
 ["Kitchen workflow","Plan preparation, cooking and storage zones around movement."],
 ["Timeless interiors","Balance personal character with a restrained material palette."],
 ["Project photography","Use original imagery to explain details clients cannot see at first glance."]
] as const;
const hashtags="#DubaiInteriors #InteriorDesignUAE #HomeRenovation";
function result<T>(data:T):GenerationResult<T>{return{data,provider:"growth1000-demo",model:"verified-template-v1",usage:{inputTokens:0,outputTokens:0,estimatedCost:0}}}
export class DemoAIProvider implements AIProvider{
 async generateSocialStrategy(context:GenerationContext,_month:string,count:number){const priorities=context.services.slice(0,4),primaryCta=context.offers.length?"Book an initial consultation":"Start a WhatsApp consultation";return result({monthlyObjective:`Increase qualified enquiries for ${priorities.slice(0,2).join(" and ")||"priority services"}.`,priorityTopics:priorities,primaryCta,contentThemes:["Practical planning","Service expertise","Design inspiration","Trust through process"],contentMix:{educational:Math.max(2,Math.round(count*.25)),service:Math.max(2,Math.round(count*.2)),problemSolution:2,projectInspiration:2,faq:1,trust:1,cta:1},performanceObservations:context.performanceContext?["Current performance signals were considered without claiming causation."]:["No connected performance signal is strong enough to guide this month."],avoidRepeating:context.recentContent?.slice(0,8)??[]})}
 async generateSocialPlan(context:GenerationContext,month:string,count:number){const excluded=new Set([...(context.recentContent??[]),...(context.businessKnowledge.match(/Recent topics: ([^.]+)/)?.[1]?.split(", ")??[])].map(x=>x.toLowerCase())),company=context.businessKnowledge.split(".")[0]?.trim()||"the client",services=context.services.slice(0,2).join(" and ").toLowerCase(),days=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0)).getUTCDate();const available=ideas.filter(([topic])=>!excluded.has(topic.toLowerCase())).slice(0,count);return result(available.map(([topic,concept],index)=>{const headline=topic.replace(/\b\w/g,c=>c.toUpperCase()),date=`${month}-${String(Math.min(days,3+index*2)).padStart(2,"0")}`;return{postNumber:index+1,contentType:index%3===0?"Carousel":"Single image",topic,objective:index%3===0?"Educate and build consideration":"Create service awareness",platform:"Instagram + Facebook",suggestedDate:date,suggestedTime:index%2?"18:30":"11:00",posterHeadline:headline,posterSupportingText:index%3===0?"A practical guide for Dubai homeowners":"",creativeBrief:`Premium editorial visual about ${topic.toLowerCase()}, created for ${company}. Warm natural light, restrained neutral palette and a clear focal point.`,imagePrompt:`Create a premium 4:5 Instagram poster for ${company}, a Dubai interior renovation company. Visual concept: ${concept} Use realistic architectural photography, warm natural lighting, refined neutral finishes and a clean composition with breathing room for the headline “${headline}”. Keep branding understated and suitable for a premium UAE interior brand. Avoid clutter, stock-photo clichés, fake before-and-after imagery, people, prices, guarantees, certifications, testimonials and excessive text.`,caption:`${concept}\n\nAt ${company}, we plan ${services||"each project"} around the way the space will be used. Save this for your planning checklist, then message us when you are ready to discuss your requirements.`,cta:"Start a WhatsApp consultation",hashtags,internalNotes:"Verify project photography and final claims before design. Human review required."}}))}
 async generateCaption(_context:GenerationContext,concept:string){return result(concept)}
 async generateCreativeBrief(_context:GenerationContext,concept:string){return result(`Editorial interior image for ${concept}; no text or unverified claims.`)}
 async generateBlogBrief(context:GenerationContext,keyword:string){return result(`Create a practical, business-friendly guide targeting “${keyword}”. Explain how homeowners can define scope, priorities and sequencing before work begins. Use only the verified services and locations in this context: ${context.services.join(", ")}. Avoid prices, guarantees, certifications, testimonials and unsupported statistics. End with a helpful consultation-focused next step.`)}
 async generateBlogDraft(context:GenerationContext,brief:string){const services=context.services.slice(0,3).join(", ");return result(`Planning a renovation starts with clarity. Before choosing finishes, define how the space needs to work, which problems matter most, and which decisions affect later stages.\n\nA useful first step is to separate essential work from optional improvements. For services such as ${services}, early measurements, storage needs and everyday routines should guide the brief. This keeps design decisions connected to practical use.\n\nSequencing matters too. Layout, services and fixed joinery decisions should be resolved before decorative details. A documented scope gives the client and implementation team a shared reference and helps surface questions while changes are still manageable.\n\nThis draft follows the approved research direction: ${brief}\n\nIf you are planning a project, prepare your priorities, reference images and practical requirements before the first consultation. The team can then discuss a suitable scope using verified project information.`)}
 async analyzeSEO(_context:GenerationContext,input:string){let keywords:Array<{keyword?:string;target_url?:string|null;current_position?:number|null}>=[];try{keywords=(JSON.parse(input) as {keywords?:typeof keywords}).keywords??[]}catch{}return result(keywords.slice(0,4).map(item=>item.current_position&&item.current_position<=20?`Strengthen ${item.target_url||"the target page"} for ${item.keyword||"the tracked keyword"} with clearer service relevance and verified proof.`:`Review search intent and on-page coverage for ${item.keyword||"the tracked keyword"} before expanding the target page.`))}
 async generateMonthlyReport(_context:GenerationContext,input:string){let facts:Record<string,unknown>={};try{facts=(JSON.parse(input) as {facts?:Record<string,unknown>}).facts??{}}catch{}const source=facts.largestLeadSource as {label?:string;count?:number}|null;return result(`${facts.clientName??"The client"} generated ${facts.leads??0} tracked enquiries this month, including ${facts.qualified_leads??0} qualified. ${typeof facts.lead_change === "number" ? `Leads changed ${facts.lead_change}% from the previous month.` : "Historical lead comparison is unavailable."}${source?` ${source.label} was the largest source with ${source.count}.`:""} The website recorded ${facts.users??"unavailable"} users and ${facts.clicks??"unavailable"} organic search clicks.`)}
}
