"use server";
import {revalidatePath} from "next/cache";
import {createClient} from "@/lib/supabase/server";
import {triggerN8nWorkflow,type N8nWorkflowKey} from "@/lib/automations/n8n";
import {syncGoogleClient} from "@/lib/google/sync";
type Result={ok:true}|{ok:false;error:string};
const workflowKeys=new Set<N8nWorkflowKey>(["MONTHLY_SOCIAL","MONTHLY_BLOG","SEO_REVIEW","MONTHLY_REPORT"]);
async function adminContext(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sign in as a partner.");const{data:membership}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).eq("role","admin").eq("status","active").limit(1).maybeSingle();if(!membership)throw new Error("An active partner membership is required.");return{supabase,organizationId:String(membership.organization_id)}}
export async function setAutomationStatus(jobId:string,status:"active"|"paused"):Promise<Result>{if(!/^[0-9a-f-]{36}$/i.test(jobId)||!["active","paused"].includes(status))return{ok:false,error:"Invalid automation update."};try{const{supabase,organizationId}=await adminContext();const{error}=await supabase.from("automation_jobs").update({status,updated_at:new Date().toISOString()}).eq("id",jobId).eq("organization_id",organizationId);if(error)return{ok:false,error:error.message};revalidatePath("/admin/automations");return{ok:true}}catch(error){return{ok:false,error:error instanceof Error?error.message:"Unable to update automation."}}}
export async function syncGoogleNow(clientId:string):Promise<Result>{if(!/^[0-9a-f-]{36}$/i.test(clientId))return{ok:false,error:"Choose a client before syncing Google data."};try{const{supabase,organizationId}=await adminContext();const{data:client}=await supabase.from("clients").select("id").eq("id",clientId).eq("organization_id",organizationId).eq("is_demo",false).eq("lifecycle_status","active").is("deleted_at",null).maybeSingle();if(!client)throw new Error("Active real client not found.");const to=new Date(Date.now()-86400000),from=new Date(to);from.setUTCDate(from.getUTCDate()-89);await syncGoogleClient(supabase,String(client.id),{from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10)},process.env,organizationId);revalidatePath("/admin/automations");revalidatePath("/admin/analytics");return{ok:true}}catch(error){return{ok:false,error:error instanceof Error?error.message:"Unable to sync Google data."}}}
export async function runAutomationNow(jobId:string,clientId:string):Promise<Result>{if(!/^[0-9a-f-]{36}$/i.test(jobId)||!clientId)return{ok:false,error:"Choose a client before running this workflow."};try{const{supabase,organizationId}=await adminContext();const{data:job}=await supabase.from("automation_jobs").select("id,workflow_key").eq("id",jobId).eq("organization_id",organizationId).maybeSingle();if(!job||!workflowKeys.has(job.workflow_key as N8nWorkflowKey))throw new Error("Automation not found.");const{data:client}=await supabase.from("clients").select("id").eq("id",clientId).eq("organization_id",organizationId).is("deleted_at",null).maybeSingle();if(!client)throw new Error("Client not found.");const month=new Date().toISOString().slice(0,7);const{data:run,error:insertError}=await supabase.from("automation_runs").insert({job_id:job.id,client_id:client.id,status:"queued",input_reference:{month},metadata:{trigger:"manual"}}).select("id").single();if(insertError)throw insertError;const input={client_id:String(client.id),month,run_id:String(run.id)};
  try{const{error:startError}=await supabase.from("automation_runs").update({status:"running"}).eq("id",run.id).eq("status","queued");if(startError)throw startError;await triggerN8nWorkflow(job.workflow_key as N8nWorkflowKey,input)}catch(error){const message=error instanceof Error?error.message:"n8n trigger failed";const{data:failed}=await supabase.from("automation_runs").update({status:"failed",finished_at:new Date().toISOString(),output_reference:{}}).eq("id",run.id).in("status",["queued","running"]).select("id");if(failed?.length)await supabase.from("automation_errors").insert({run_id:run.id,error_code:"TRIGGER_FAILED",message,details:{retryable:true}});revalidatePath("/admin/automations");return{ok:false,error:message}}
  revalidatePath("/admin/automations");return{ok:true}
 }catch(error){return{ok:false,error:error instanceof Error?error.message:"Unable to start automation."}}}
