"use server";
import {revalidatePath} from "next/cache";import {createClient} from "@/lib/supabase/server";import {DemoAIProvider} from "@/lib/ai/demo-provider";import {prepareMonthlySocial} from "@/lib/ai/monthly-social";import {createAIProvider,type GenerationContext} from "@/lib/ai/provider";import type {SocialPost} from "@/lib/social-store";
type Result={ok:true}|{ok:false;error:string};
async function contextFor(clientId:string){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sign in as a partner.");const{data:membership}=await supabase.from("organization_members").select("organization_id").eq("user_id",user.id).eq("role","admin").eq("status","active").limit(1).maybeSingle();if(!membership)throw new Error("An active partner membership is required.");const{data:client}=await supabase.from("clients").select("id,name,industry,city").eq("id",clientId).eq("organization_id",membership.organization_id).is("deleted_at",null).single();if(!client)throw new Error("Client not found.");return{supabase,user,client}}
export async function saveSocialContent(post:SocialPost,status:string):Promise<Result>{if(typeof post.id!=="string"||!/^[0-9a-f-]{36}$/i.test(post.id)||!post.clientId)return{ok:false,error:"Invalid content item."};try{const{supabase,client}=await contextFor(post.clientId);const allowed=new Set(["idea","generating","needs_review","approved","ready_to_post","scheduled","published","issue"]);if(!allowed.has(status))return{ok:false,error:"Invalid content status."};const{error}=await supabase.from("content_items").update({topic:post.topic,concept:post.concept,caption:post.caption,hashtags:post.hashtags,creative_brief:post.creativeBrief,internal_notes:post.notes,status}).eq("id",post.id).eq("client_id",client.id);if(error)return{ok:false,error:error.message};revalidatePath("/admin/content");revalidatePath("/staff");return{ok:true}}catch(error){return{ok:false,error:error instanceof Error?error.message:"Unable to save social content."}}}
export async function regenerateSocialCreative(contentId:string,clientId:string):Promise<{ok:true;image:{version:number;status:SocialPost["imageStatus"];model:string;storagePath:string|null}}|{ok:false;error:string}>{if(!/^[0-9a-f-]{36}$/i.test(contentId))return{ok:false,error:"Invalid social content."};try{const{supabase,client}=await contextFor(clientId);const{data:content}=await supabase.from("content_items").select("id").eq("id",contentId).eq("client_id",client.id).eq("content_kind","social_post").maybeSingle();if(!content)return{ok:false,error:"Social content not found."};const{data,error}=await supabase.rpc("regenerate_social_image",{target_content:contentId,requested_model:process.env.IMAGE_MODEL??process.env.AI_MODEL??"placeholder"});if(error)return{ok:false,error:error.message};const row=Array.isArray(data)?data[0]:data;if(!row)return{ok:false,error:"Image version was not created."};const rawStatus=String(row.image_status),status:SocialPost["imageStatus"]=rawStatus==="generated"?"Generated":rawStatus==="failed"?"Failed":"Placeholder";revalidatePath("/admin/content");return{ok:true,image:{version:Number(row.image_version),status,model:String(row.image_model),storagePath:row.image_storage_path?String(row.image_storage_path):null}}}catch(error){return{ok:false,error:error instanceof Error?error.message:"Unable to regenerate image."}}}
export async function generateSocialMonth(clientId:string,month:string):Promise<Result>{
 if(!/^\d{4}-\d{2}$/.test(month))return{ok:false,error:"Choose a valid month."};
 try{const{supabase,user,client}=await contextFor(clientId),monthStart=`${month}-01`;const{count,error:countError}=await supabase.from("content_items").select("id",{count:"exact",head:true}).eq("client_id",clientId).eq("content_kind","social_post").eq("month",monthStart);if(countError)return{ok:false,error:countError.message};if(count)return{ok:false,error:"This month already has social content. Review existing items instead of replacing them."};
  const[{data:profile},{data:services},{data:recent}]=await Promise.all([supabase.from("business_profiles").select("description,value_proposition,offers,prohibited_claims").eq("client_id",clientId).maybeSingle(),supabase.from("business_services").select("name").eq("client_id",clientId),supabase.from("content_items").select("topic").eq("client_id",clientId).eq("content_kind","social_post").order("created_at",{ascending:false}).limit(24)]);
  const generationContext:GenerationContext={clientId,businessKnowledge:[client.name,client.industry,client.city,profile?.description,profile?.value_proposition,`Recent topics: ${(recent??[]).map(row=>row.topic).filter(Boolean).join(", ")}`].filter(Boolean).join(". "),services:(services??[]).map(row=>String(row.name)),offers:Array.isArray(profile?.offers)?profile.offers.map(String):[],prohibitedClaims:Array.isArray(profile?.prohibited_claims)?profile.prohibited_claims.map(String):[]};const provider=process.env.AI_API_KEY?createAIProvider():new DemoAIProvider();const plan=await prepareMonthlySocial(provider,month,12,generationContext);
  const rows=plan.concepts.map((item,index)=>({client_id:clientId,content_kind:"social_post",month:monthStart,platform:index%3===0?"Instagram + Facebook":"Instagram",topic:item.topic,concept:item.concept,caption:item.caption,hashtags:item.hashtags,creative_brief:item.creativeBrief,recommended_publish_at:new Date(`${month}-${String(3+index*2).padStart(2,"0")}T11:00:00+04:00`).toISOString(),internal_notes:`Generated by ${plan.provider} · ${plan.model}. Human internal review required.`,status:"needs_review",created_by:user.id}));const{error}=await supabase.from("content_items").insert(rows);if(error)return{ok:false,error:error.message};revalidatePath("/admin/content");return{ok:true};
 }catch(error){return{ok:false,error:error instanceof Error?error.message:"Unable to prepare the social month."}}
}
